/*
** vars.c for vars in /home/fredoddou/Documents/Epitech/B4-Unix-System-Programming/PSU_2016_philo/src/
**
** Made by Frederic ODDOU
** Login oddou_f <frederic.oddou@epitech.eu>
**
** Started on  Wed Mar 15 11:42:19 2017 Frederic ODDOU
** Last update Wed Mar 15 11:42:19 2017 Frederic ODDOU
*/

#include <stdlib.h>

size_t		tab_len(char **tab)
{
  size_t	i;

  i = 0;
  while (tab[i])
    i++;
  return (i);
}

char	*g_repas[] = {
  "Riz",
  "Nuggets de poulet",
  "Pizza",
  "Sushis",
  "Nems",
  "Makis",
  "Steak hache",
  "Petit poids",
  "Carottes",
  "Maxi big mac",
  "McFleury",
  "Frites",
  "Tenders",
  "Wings",
  "Panini",
  "Boeuf bourguignon",
  "Haricots verts",
  "Crepes",
  "Huitre",
  "Fois gras",
  "Patates",
  "Muffing",
  "Bananes",
  "Fraises",
  "Chocolat",
  "Chantilly",
  "Smoothie",
  "Nutella",
  "Browies",
  "Couscous",
  "Paela",
  "Jambon",
  "Pates",
  "Salade",
  "Hamburgers",
  "Sandwichs",
  "Fondue chinoise",
  "Risotto",
  "Ramene",
  "Saucices",
  "Mergez",
  "Crevettes",
  "Tapas",
  "Chips",
  "Saumon",
  "Filet de cabillaud",
  "Blanc de poulet",
  "Cake",
  "Poisson pane",
  "Tomates",
  "Moules",
  "Crabe",
  "Langoustine",
  "Palourdes",
  "Morue",
  "Boeuf",
  "Rumsteck",
  "Bacon",
  "Canard",
  "Cuisse de poulet",
  "Agneau",
  "Fajitas",
  "Flageolets",
  "Sub Taz",
  NULL
};

char	*g_names[] = {
  "Anakin",
  "Vador",
  "Jean",
  NULL
};

char	*g_citations[] = {
  "Y a-t-il des etoiles au paradis ?",
  "La soupe de fraise aux fraises est-elle dangereuse pour les chiens de \
traîneau ?",
  "Pourquoi les animaux sont-ils nudistes ?",
  "Où trouver un paysage demontable ?",
  "Pourquoi Elsa Triolet a-t-elle six yeux ?",
  "Comment appelle-t-on les annees comportant cinq saisons ?",
  "Le nombre 256232584215689 est-il divisible par le bonheur ?",
  "Le titre de < roi des animaux > est-il hereditaire ?",
  "L'impossible est-il elitiste ?",
  "La vie est-elle une exception ?",
  "Quel est le contraire d'Alfred ?",
  "Les singes sont-ils racistes ?",
  "Les mots croises sont-ils de gauche ou de droite ?",
  "A quelle date Einstein reviendra-t-il sur Terre ?",
  "Le rire est-il un agent double ?",
  "D'où vient l'eternite ?",
  "Peut-on faire de l'alcool avec le raisin d'ours ?",
  "Qui a vote la loi des series ?",
  "Faut-il canoniser Coluche ?",
  "Le prochain train de mesures arrivera-t-il a l'heure ?",
  "Les oeufs d'archeopteryx etaient-ils comestibles ?",
  "Les abeilles ont-elles un Intranet ?",
  "Preferez-vous le harem bi ou le classique ?",
  "La peche a la ligne est-elle imprimable ?",
  "Peut-on franchir le mur de la connerie ?",
  "Avez-vous deja embrasse un scarabee ?",
  "Les jumelles a infrarouges sont-elles homozygotes ou heterozygotes ?",
  "Les chaussettes de l'archiduchesse secheront-elles avant la fin du monde ?",
  "Preferez-vous le theâtre des operations ou le cirque de Gavarnie ?",
  "Le cerveau est-il une prison pour les images ?",
  "Comment devient-on passeur de reves ?",
  "En quelle annee l'île de la Cite larguera-t-elle ses amarres ?",
  "Dans quel pays les gauchers applaudissent-ils d'une seule main ?",
  "Peut-on parler deux langues a la fois ?",
  "Peut-on tuer le temps sans etre poursuivi en justice ?",
  "La poesie peut-elle sauver les tickets de metro ?",
  "Les puces electroniques ont-elles le droit de tester les insecticides ?",
  "Le pain est-il plus facile a rompre que le silence ?",
  "La memoire est-elle soluble dans la matiere ?",
  "Quarante-deux est-il un bon chiffre pour les analphabetes ?",
  "Savez-vous lire l'avenir dans les globules rouges ?",
  "Le sommeil est-il nuisible au reel ?",
  "Les veterinaires de l'ere tertiaire etaient-ils syndiques ?",
  "Qui a invente Venise ?",
  "Les regles de conduite s'arretent-elles a la menopause ?",
  "Le temps des cerises est-il courbe ?",
  "En quelle annee Le livre de la Jungle a-t-il ete traduit en arameen ?",
  "La vie sur Mars est-elle basee sur l'ADN ?",
  "Les caramels mous sont-ils hallucinogenes ?",
  "A quelle banque faut-il rapporter les euros emis avant 2003 ?",
  "Les vaches aiment-elles la musique militaire ?",
  "Les garçons de plage ont-ils le droit de greve ?",
  "Les fautes d'orthographe donneront-elles un jour des points au \
baccalaureat ?",
  "Peut-on civiliser les fleurs sauvages ?",
  "Combien vaut un billet d'avion pour l'Atlantide ?",
  "Napoleon a-t-il existe ?",
  "Que faire quand les coups de pied sont plus nombreux que les \
fourmilieres ?",
  "A quelle heure doit-on se raser quand on a un poil dans la main ?",
  "Quel est le record du monde de plongee dans l'inconscient ?",
  "La roue a-t-elle toujours ete ronde ?",
  "Quelle question poseriez-vous au Diable si vous le rencontriez a l'Opera ?",
  "a quel moment de l'annee ont lieu les soldes de tout compte ?",
  "Le courant alternatif est-il favorable au Commerce equitable ?",
  "Les comiques ont-ils de l'humour ou des factures a payer ?",
  "Les impôts sur les semences sont-ils un facteur de decroissance ?",
  "Connaissez-vous un psychanalyste pour herbes folles ?",
  "Que s'est-il passe en 2028 ?",
  "Quelle est la future capitale de la France ?",
  "Existe-t-il des prostituees chez les mouches heterosexuelles ?",
  "Haendel parlait-il l'argot londonien ?",
  "Comment Zenon formulait-il le paradoxe des refrigerateurs au pôle nord ?",
  "Les moustiques peuvent-ils se marier entre cousins ?",
  "Les arcs-en-ciel possedent-ils une couleur tertiaire ?",
  "A quoi pense une rascasse avant de plonger dans la bouillabaisse ?",
  "Les serre-livres ont-ils raison ?",
  "La barbe de Madame de Pompadour etait-elle postiche ?",
  "Combien de tomes y a-t-il dans une livre de fromages ?",
  "Aimez-vous l'odeur de la foule apres la pluie ?",
  "Peut-on arreter les cometes en plein vol ?",
  "Les îles Vierges portent-elles des ceintures de chastete ?",
  "La grammaire generative est-elle un facteur de cohesion sociale ?",
  "Marx etait-il marxiste ?",
  "Le Corbeau et le Renard sont-ils en couple ?",
  "Tintin a-t-il fait vacciner Milou ?",
  "Le mensonge est-il un passe-temps ou une esthetique ?",
  "Les vieilles dames du Puy-en-Velay ont-elles un permis de dentelle ?",
  "Le tourisme animal est-il rentable ?",
  "Le jeu de l'oie est-il dangereux pour les enfants precoces ?",
  "Peut-on conserver l'huile sur le feu pour les jours où les epoux se \
frittent ?",
  "L'histoire est-elle une imposture, un combat ou une utopie ?",
  "La nature est-elle capable d'imiter l'art ?",
  "La nudite est-elle un manque d'imagination ?",
  NULL
};
